apiVersion: v1
kind: Service
metadata:
  namespace: ssms
  labels:
    app.kubernetes.io/name: ssms-api
    app.kubernetes.io/part-of: com.abduldevelops.ssms.api
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: ssms-api
spec:
  ports:
    - name: ssms-api-port
      port: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: ssms-api
    app.kubernetes.io/part-of: com.abduldevelops.ssms.api
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: LoadBalancer