apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ssms-api
    app.kubernetes.io/part-of: com.abduldevelops.ssms.api
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: ssms-api
  namespace: ssms
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0-SNAPSHOT
      app.kubernetes.io/part-of: com.abduldevelops.ssms.api
      app.kubernetes.io/name: ssms-api
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 1.0-SNAPSHOT
        app.kubernetes.io/part-of: com.abduldevelops.ssms.api
        app.kubernetes.io/name: ssms-api
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: postgres-configuration
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-credentials

          image: 4bdu1/ssms-api
          imagePullPolicy: IfNotPresent
          name: ssms-api
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"