custom_build(
    '4bdu1/ssms-api',
    'mvn jib:dockerBuild -Djib.to.tags=latest,1.0-SNAPSHOT,$EXPECTED_TAG -f ../../ssms-service/ssms-container/pom.xml',
    deps=['../../ssms-service/ssms-container/src']
    )

k8s_yaml(kustomize('./kustomization/base'))
k8s_resource('ssms-api', port_forwards=8080)